require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ExerciseProgramsController, type: :controller do

  let!(:test_user) do
    User.create(email:"bob@bob.com",
    password: "qwerty",
    password_confirmation: "qwerty")
  end

  before(:each) do
    sign_in test_user
  end

  # This should return the minimal set of attributes required to create a valid
  # ExerciseProgram. As you add validations to ExerciseProgram, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    #skip("Add a hash of attributes valid for your model")#<--this is the message that will be shown from you skipping
#    {}
    #WHOA WE'RE NOT SKIPPING ANYTHING
    {user_id: test_user.id}
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
#todo: how to break user_id    
#    {user_id: -5}
#    {user_id: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseProgramsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      exercise_program = ExerciseProgram.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      exercise_program = ExerciseProgram.create! valid_attributes
      get :show, params: {id: exercise_program.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      exercise_program = ExerciseProgram.create! valid_attributes
      get :edit, params: {id: exercise_program.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ExerciseProgram" do
        expect {
          post :create, params: {exercise_program: valid_attributes}, session: valid_session
        }.to change(ExerciseProgram, :count).by(1)
      end

      it "redirects to the created exercise_program" do
        post :create, params: {exercise_program: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ExerciseProgram.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {exercise_program: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exercise_program" do
        exercise_program = ExerciseProgram.create! valid_attributes
        put :update, params: {id: exercise_program.to_param, exercise_program: new_attributes}, session: valid_session
        exercise_program.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the exercise_program" do
        exercise_program = ExerciseProgram.create! valid_attributes
        put :update, params: {id: exercise_program.to_param, exercise_program: valid_attributes}, session: valid_session
        expect(response).to redirect_to(exercise_program)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        exercise_program = ExerciseProgram.create! valid_attributes
        put :update, params: {id: exercise_program.to_param, exercise_program: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested exercise_program" do
      exercise_program = ExerciseProgram.create! valid_attributes
      expect {
        delete :destroy, params: {id: exercise_program.to_param}, session: valid_session
      }.to change(ExerciseProgram, :count).by(-1)
    end

    it "redirects to the exercise_programs list" do
      exercise_program = ExerciseProgram.create! valid_attributes
      delete :destroy, params: {id: exercise_program.to_param}, session: valid_session
      expect(response).to redirect_to(exercise_programs_url)
    end
  end

end
